### ISSUE TITLE
Support Width = * and Width = AUTO

### ISSUE THREAD

**Issue by Bush-cat** [w-ahmad/WinUI.TableView#10]
**Is your feature request related to a problem? Please describe.**
I used both with the Datagrid from CommunityToolkit.WinUI.UI.
Width = * made it use the full available space in the window, if you have two columns with Width = * they would each use half of the window
Width = Auto made the Column the samllest width it needed to fit the Text and Buttons

**Describe the solution you'd like**
Support both to work like other common controls as described above.

**Comment by uixiu** [comment]
Width="NaN" will auto resize the content column, but not the header column, which should be resized manually AFAIK.

<img width="828" alt="Screenshot 2024-06-01 161656" src="https://github.com/w-ahmad/WinUI.TableView/assets/41270525/85b9d790-f1b0-4f69-8b19-6cab3419e2d1">
