### ISSUE TITLE
Add Cell Selection Support

### ISSUE THREAD

**Issue by w-ahmad** [w-ahmad/WinUI.TableView#12]
### Problem Statement
Currently, the WinUI.TableView control does not support the selection of individual cells. This limitation restricts the ability to perform cell-specific operations, which are common in data grid scenarios.

### Proposal
Implement cell selection functionality to enhance the control's interactivity and usability. This will allow users to select a single cell or multiple cells using keyboard shortcuts or mouse actions. It would bring WinUI.TableView in line with other DataGrid controls.

### Key Features
* Individual cell selection
* Multi-cell selection
* Range selection
* Extended range selection
* Copy and Export actions on selected cells

**Comment by weiyoucheng** [comment]
I really need this feature. When can I add it

**Comment by w-ahmad** [comment]
@weiyoucheng Thanks for checking out WinUI.TableView! You can try out cell selection in v1.2.0-preview1.

**Comment by weiyoucheng** [comment]
This is a great feature, but it seems not quite perfect yet, as it is unable to copy the content of the cell with the Ctrl + C shortcut. Selecting cells is mainly for the convenience of quickly copying data, but it's quite regrettable that I didn't get the cell content data when copying with Ctrl + C. Can the feature of copying cell content be added in the future?

**Comment by w-ahmad** [comment]
@weiyoucheng I'm pretty sure it was working when I gave it a shot. Did you try copying the cell content from the options button?

**Comment by weiyoucheng** [comment]
![image](https://github.com/w-ahmad/WinUI.TableView/assets/112521929/a0801e3d-fb37-4482-9f11-f8498305679d)
![image](https://github.com/w-ahmad/WinUI.TableView/assets/112521929/57dd98ec-c49b-4d4f-9d25-ab49d2b7e582)
Do you mean setting the SelectionMode to 'Multiple' when you suggest trying to copy the cell content from the options button?
I have tried it, but none of them have obtained the cell content.

**Comment by w-ahmad** [comment]
@weiyoucheng I've opened a new issue #25 related to short keys and hopefully it will be fixed in the next release.

**Comment by lostluna1** [comment]
![QQ20240901-192628](https://github.com/user-attachments/assets/620fc400-9de3-4c97-ac29-b137a0fc4d69)
IsMultiSelectCheckBoxEnabled properties look like inactive
