### ISSUE TITLE
Additional coloring

### ISSUE THREAD

**Issue by Petrarca181** [w-ahmad/WinUI.TableView#21]
**Is your feature request related to a problem? Please describe.**
Hello, will be nice to have alternate row  foreground/background coloring.  And vertical  + horizontal bars option. 

**Additional context**
I think it's important for long tables readability.

**Comment by w-ahmad** [comment]
I just found out about an extension in the Community Toolkit that allows you to set alternate colors on a ListView. Although I haven't tested it yet, it seems like it's worth giving a shot.

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/windows/extensions/listviewextensions#alternatecolor

I'll make an effort to include alternating row colors and grid lines in the next major release.
