### ISSUE TITLE
ShowOptionsButton functionality

### ISSUE THREAD

**Issue by tinmac** [w-ahmad/WinUI.TableView#23]
**Describe the solution you'd like**
`ShowOptionsButton = false` will hide the three dots icon but in its place shows the `Select all` icon
I would like to hide both these icons, is this possible? 

**Additional context**
Thankyou for your time and effort creating this control, it is much appreciated

**Comment by w-ahmad** [comment]
@tinmac Thank you for your interest in WinUI.TableView. Unfortunately, there is currently no feature to hide the `Select All` icon or button from the control. However, I plan to introduce a property to hide this button in a future release.
