### ISSUE TITLE
Small spelling mistake

### ISSUE THREAD

**Issue by GuildOfCalamity** [w-ahmad/WinUI.TableView#31]
Sorry, I hate to be "that guy", but in your **MainWindow.xaml** you have `Content="Laod More Items"`
Also, in the T**ableViewCell.cs**, I think this would be an improvement...
```
    internal async void PrepareForEdit()
    {
        SetEditingElement();
        await Task.Delay(20);
        if ((Content ?? ContentTemplateRoot) is UIElement editingElement)
        {
            editingElement.Focus(FocusState.Programmatic);
            if (editingElement is TextBox tb && !string.IsNullOrEmpty(tb.Text))
                tb.SelectAll();
        }
    }
```
I've also added some general improvements [here](https://github.com/GuildOfCalamity/WinUI.TableView/commit/3c55cce5d063c961f7a332999e4c950ec31cbf90) like a switch for for single-click editing and the **TextBox.SelectAll()** example above.

**Comment by GuildOfCalamity** [comment]
I've also added some general improvements [here](https://github.com/GuildOfCalamity/WinUI.TableView/commit/3c55cce5d063c961f7a332999e4c950ec31cbf90)

**Comment by w-ahmad** [comment]
This issue will be closed after correcting the spelling errors. Perhaps the `TextBox.SelectAll()` feature will be considered for the next major release.
