### ISSUE TITLE
Cellmarker + Navigation in R/O-Mode

### ISSUE THREAD

**Issue by VisualAlf** [w-ahmad/WinUI.TableView#46]
I'm using TableView mostly as an enhancement to plain ListView, so I'll set Readonly=true, SelectionMode=Single and SelectionUnit=Row.

I think, this mode has not really a concept of a Cell (except maybe for clipboard copying). 

So, I'd like to have an option to 
1. turn the cellmarker off. 
2. have keyboard navigate by row (and not by cell) and 
3. a click on any cell would select the complete row. 

I'd tried 'SingleSelectionFollowsFocus= true', but that had issues with keyboardnavigation.

I've seen the source for navigation seems pretty complicated, but perhaps you can provide a solution; I'd greatly appreciate.

**Comment by w-ahmad** [comment]
Thank you @VisualAlf for your suggestion, it means a lot to improve the product. I made some efforts to fulfill your requirements and hopefully will be available soon in the next service release.

**Comment by VisualAlf** [comment]
Thank you, @w-ahmad for labor and time.

But,
that's not what I'm after. Perhaps I can explain better?

What I meant with 'Cellmarker' is really the standard KeyboardFocusRectangle in WinUI. You seem to use it as sort of 'Current-Cell' marker. 

Now my use-case is sort-of Master-Detail. For example, I display a collection of invoices (e.g. table of rows). The user selects an invoice (a specific ROW in the table) and the app then does whatever it is to, with that invoice. 

When the user clicks into the row, s/he should see the **_row_** selected (and not the **_cell_**), since interest is in the whole Invoice (row), not in the property (cell) of that invoice, that the user happened to click in.  That also makes the keyboard focus unnecessary and even distracting. 
Any click in the row should select that row, regardless of which cell was clicked.

Also, since the interest is rows, there is no point to move the 'current cell pointer' to right or left. Which means, that Arrows R/L and Tab/Shift Tab should be off function. Up/Down arrows should move the pointer to prev/next row. (As they do just now).

As a possible solution I can think of 
1. switch the Keyboard-focus-rectangle off, when `Readonly=true` (or use a DepProp for that). Note, there is still the hoover mark on the 'current' cell, so we know where we are.
2. Alternatively, consider showing the Keyboard-focus-rectangle only, when there is a keyboard action, or a double-click for editing. Also, hide it, when focus leaves the table. That seems to be the standard behavior in windows.
3.  in 'Single row' mode, always select the current row (and make that visible) whenever there is a click. (Maybe, that extents to the other modes as well, haven't thought that through.)

Again, many thanks to you. I really like the component.

**Comment by w-ahmad** [comment]
Thank you so much @VisualAlf for the detailed explanation.

What I understand is that you are trying to use this control as `ListView` but with the columns like `TableView`, and editing cell value is not your main concern. If that's the case, you can achieve `ListView` like functionality by setting `SelectionUnit = Row` and `IsReadOnly = true` on TableView. This will act like there are no cells in the row at all and by clicking anywhere in the row, it will be selected if the `SelectionMode` isn't set to `None`.

![Animation](https://github.com/user-attachments/assets/0fae8563-8df6-4b93-b542-6efb38b8d84e)

**Comment by VisualAlf** [comment]
Thanks again @w-ahmad , much appreciated. 

Looking forward for 1.3. since I seem to not being able to generate a usable pack for local Nuget feed.

**Comment by w-ahmad** [comment]
@VisualAlf you can try this out in v1.2.1.

**Comment by VisualAlf** [comment]
nice, thanks.
