### ISSUE TITLE
About IsReadOnly

### ISSUE THREAD

**Issue by lostluna1** [w-ahmad/WinUI.TableView#63]
**Is your feature request related to a problem? Please describe.**
When the column property of the table is set to IsReadOnly, there is no change in the row style of the table

**Describe the solution you'd like**
When the column property of the table is set to IsReadOnly, the row style of the table becomes gray

**Comment by w-ahmad** [comment]
I think the row or cell should only become gray if those are disabled, read-only shouldn't change any style.

**Comment by lostluna1** [comment]
Please consider the cell style when IsReadOnly , so that it is consistent with the IsReadOnly  behavior of other controls, as I plan to implement design permission control. Without style differentiation, IsReadOnly  will cause confusion for users

**Comment by lostluna1** [comment]
> 请考虑 IsReadOnly 时的单元格样式，使其与其他控件的 IsReadOnly 行为一致，因为我计划实现设计权限控制。如果没有样式区分，IsReadOnly 会给用户带来混淆

Perhaps I should set cells to disabled when I do not have the corresponding permissions?

**Comment by lostluna1** [comment]
example:
```c#
<table:TableViewTextColumn IsReadOnly="True"
                           Width="*"
                           Binding="{Binding EmployeeCode}"
                           l:Uids.Uid="EmployeeCodeTextBox"
                           />
``` 
not supported IsEnable Properties

**Comment by lostluna1** [comment]
I think I know what to do, please ignore my request.
