### ISSUE TITLE
Memory usage and screen freezes

### ISSUE THREAD

**Issue by VisualAlf** [w-ahmad/WinUI.TableView#64]
I experience massive memory usage increases and screen freezes, when a page with the tableview is shown for a 2nd (and further) time. 
It may be, there's a memoryleak. There may be also some heavy GC.
Unfortunately, I'm not clever enough to find out what really happens. I'm afraid, that at least in the current version, I may not be 
able to include the TableView into my current project. 

I've appended a demo-project that simply has 2 pages - home page is empty, - other page holds the code from the SampleApp. For the demonstration of the effect, just switch 2 or 3 times between the 2 pages. Also monitor the diagnostics in VS.
[MemIssueTableView.zip](https://github.com/user-attachments/files/17826784/MemIssueTableView.zip)

I do hope we'll find something out...

**Comment by w-ahmad** [comment]
Thanks @VisualAlf for your feedback. 

It looks like WinUI doesn't like despondency properties. The `TableView` properties of Row and Cell are causing memory leaks, if I convert these properties to standard properties it works without any issue and there are less memory footprints as well.
