### ISSUE TITLE
Width of TableView changes 

### ISSUE THREAD

**Issue by VisualAlf** [w-ahmad/WinUI.TableView#78]
... more an irritation than a bug...

An empty TV shows without vertical scrollbar. However scrollbar appears as soon as data appears. That makes the Width of the TV widen or shrink. Doesn't hurt but looks a bit unprofessional, IMHO. 
I have some use-cases where the TV is empty at times, so I've noticed.

**Comment by w-ahmad** [comment]
It doesn't make any sense to me. could you upload some screenshots or recordings please?

**Comment by w-ahmad** [comment]
how should it deal with scrollbars? I believe this is the way how layout of scroll viewer works. try ListView instead of TableView in your example and set minwidth = 230. you will notice the same behavior.

**Comment by VisualAlf** [comment]
Seems, the reason is the Grid.Columndefinition. If I set `Width="<somefixedvalue>"` instead of `Width="Auto" `the behavior is gone. 
So this isn't an issue with TableView. 
Closing now, thanks for your time.
